name: Build

on:
  push:
    branches:
      - main
    paths:
      - "**.nix"
      - flake.lock
      - .github/workflows/*.yml
  merge_group:
  pull_request:
    branches: ["*"]
    paths:
      - "**.nix"
      - flake.lock
      - .github/workflows/*.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: [X64, Linux]

    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/nix-installer-action@v20
        with:
          source-url: https://install.lix.systems/lix/lix-installer-x86_64-linux
          diagnostic-endpoint: ""
          extra-conf: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= just-one-more-cache.cachix.org-1:4nShcKEgcUEVlJqKFrgDwoGfqLnw5KPG4UDTV02jnr4=
            substituters = https://cache.nixos.org/ https://just-one-more-cache.cachix.org/
      - uses: yaxitech/nix-install-pkgs-action@v7
        with:
          packages: "nixpkgs#omnix"
      - run: |
          set -euxo pipefail
          om ci run --include-all-dependencies -- --show-trace
